// import Head from "next/head"; 
// import Script from "next/script";

import Nav from "./components/nav";
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata = {
  title: 'Steve Ditlea Journalist @ Large',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <Header />
        {children}
        <Footer />
       </body>
    </html>
  )
}
